# Generated by Django 5.0 on 2024-06-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=20),
        ),
    ]
